efabless/openlane2

.readthedocs.yml, Readme.md
* Ports over `.readthedocs.yml` from OpenLane 1
* Updates Readme to use RTD links for documentation
=> Attempt to Fix RTD

Changelog.md, openlane/__version__.py, openlane/config/builder.py
If `dirname` returns an empty string, the flow would crash. I moved the abspath earlier.
=> Fix a small path resolution issue

openlane/scripts/klayout/stream_out.py
If the `os.path.abspath` is added to the `design_name`, then this causes a fail of the GDS write by `klayout` (see Slack discussion with @donn).
Same issue happens in `OL1`, and is addressed by https://github.com/The-OpenROAD-Project/OpenLane/pull/1731
=> Fix GDS write fail by KLayout

Changelog.md, openlane/__version__.py, openlane/scripts/klayout/open_design.py, openlane/scripts/klayout/render.py
This is not strictly necessary as that variable is not used in those scripts yet, but won't hurt for the future.
=> Apply `stream_out` fix to other KLayout scripts

openlane/__main__.py, openlane/config/builder.py
Includes 34341ce66c36b506f43276486b177b1adcd6ed8b, which was pushed to main by accident
---
* Updated the smoke test to support PDK downloads to a different directory.
* Updated config builder to resolve the PDK root much earlier to avoid an issue where a crash would affect the issue reproducible.
* Updated `SYNTH_READ_BLACKBOX_LIB` to read the full `LIB` variable instead of `LIB_SYNTH`, which also fixes a crash when reading JSON headers.
* Updated post-GRT resizer timing script to re-run GRT before the repair: see https://github.com/The-OpenROAD-Project/OpenROAD/issues/3155
* Added a "yosys proc" to the JSON header generator (thanks @smnaut)
* Fixed a bug where random equidistant mode did not work for OpenROAD IO placer.
---
Resolves #40, Resolves #38
=> Assorted Bugfixes

.readthedocs.yml, Changelog.md, Makefile, default.nix, openlane/__main__.py, openlane/__version__.py, openlane/config/builder.py, openlane/config/config.py, openlane/config/variable.py, openlane/flows/flow.py, openlane/flows/sequential.py, openlane/state/state.py, openlane/steps/checker.py, openlane/steps/step.py, openlane/steps/tclstep.py, requirements.txt, requirements_dev.txt, requirements_docs.txt
* Added `cloup` library for better argument grouping/prettier `--help` with click
* Added ability to substitute steps with a certain `id` in a `SequentialFlow`
with other Step classes
* Added `--only`, `--skip` to commandline interface for `SequentialFlow`s
* Changed processing of how `--from` and `--to` are done in `SequentialFlow`s
* Better delineation of class vs. instance variables in documentation
* Type checker now also checks functions without typed headers
* Fixed minor bugs with `Decimal` serialization and deserialization
* Class/step registry now case-insensitive
* Moved documentation dependencies to separate requirements file
* Removed `jupyter` from `requirements_dev.txt`- too many dependencies and can
just be installed with `pip install jupyter`
* Various documentation …
=> `SequentialFlow` Ergonomics

Changelog.md, docs/source/usage/hardening_macros.md, openlane/__main__.py, openlane/__version__.py, openlane/common.py, openlane/container.py, openlane/flows/flow.py, openlane/flows/sequential.py, openlane/logging.py, openlane/scripts/openroad/drt.tcl, openlane/steps/openroad.py, openlane/steps/step.py, openlane/steps/tclstep.py
* Added a commandline option `-j/--jobs` to add a maximum cap on subprocesses.
* Added a global ThreadPoolExecutor object for all subprocesses to `common`.
* Accessible for external scripts and plugins via `openlane.get_tpe` and `openlane.set_tpe`
* Folded `--list-plugins` into `--version`
* Renamed `ROUTING_CORES` to `ROUTING_THREADS`
* Removed `RCX_CORES`, step now uses global ThreadPoolExecutor
=> Better Thread Handling

Changelog.md, designs/xtea/src/xtea.sdc, openlane/__version__.py, openlane/scripts/base.sdc, openlane/scripts/openroad/common/io.tcl, openlane/scripts/openroad/cts.tcl, openlane/scripts/yosys/synthesize.tcl
* Added `MAX_TRANSITION_CONSTRAINT` to `base.sdc` (if set)
* Added `MAX_TRANSITION_CONSTRAINT` -> `SYNTH_MAX_TRAN` translation behavior in `base.sdc`
* Removed attempt(s) to calculate a default value for `MAX_TRANSITION_CONSTRAINT` in `all.tcl`, `openroad/cts.tcl` and `yosys/synth.tcl`
=> Fix Max Transition Setting

Changelog.md, openlane/__version__.py, openlane/common.py, openlane/scripts/odbpy/reader.py, openlane/scripts/openroad/common/io.tcl, openlane/scripts/openroad/floorplan.tcl, openlane/scripts/openroad/rcx.tcl, openlane/scripts/openroad/sta/corner.tcl, openlane/scripts/openroad/sta/multi_corner.tcl, openlane/scripts/openroad/sta/multi_corner.tcl.bk, openlane/steps/checker.py, openlane/steps/magic.py, openlane/steps/odb.py, openlane/steps/openroad.py, openlane/steps/step.py, openlane/steps/tclstep.py, openlane/utils/toolbox.py
* Added mechanism for subprocesses to write metrics via stdout, `%OL_METRIC{,_I,_F}`, used for OpenSTA
* Added violation summary table to post-PNR STA
* Reworked multi-corner STA: now run across N processes with the step being responsible for aggregation
* Made handling `Infinity` metrics more robust
* Fixed names of various metrics to abide with conventions:
* `magic__drc_errors` -> `magic__drc_error__count`
* `magic__illegal__overlaps` -> `magic__illegal_overlap__count`
* Removed splash messages from OpenROAD, OpenSTA
---
Resolves #42
=> STA Metrics, Aggregation and Summary Table

Changelog.md, designs/y_huff/config.json, openlane/__version__.py, openlane/scripts/openroad/common/resizer.tcl, openlane/scripts/openroad/repair_design.tcl, openlane/scripts/openroad/rsz_timing_postcts.tcl, openlane/scripts/openroad/rsz_timing_postgrt.tcl, openlane/steps/common_variables.py, openlane/steps/openroad.py, openlane/steps/step.py, openlane/utils/drc.py
* Made Magic DRC report parser more robust, handling multiple rules, etc
* Updated documentation for various related variables
* Fixed bug causing PNR-excluded cells being used during resizer-based OpenROAD steps
---
Resolves #106
=> Fix Resizer Step Bug + DRC Report Parsing

Changelog.md, openlane/__main__.py, openlane/__version__.py, openlane/flows/__init__.py, openlane/flows/cli.py, openlane/flows/flow.py, openlane/flows/sequential.py, openlane/logging/__init__.py, openlane/state/state.py, requirements.txt
* Created `openlane.flows.cloup_flow_opts`, which assigns a number of `cloup`
commandline options to an external function for convenience.
* Moved handling of `last_run` inside `Flow.start`
* Moved handling of volare, setting log level and threadpool count to `cloup_flow_opts`
=> Add public CLI parse helper

.github/test_sets/test_sets.yml, Changelog.md, designs/test_sram_macro/config.json, openlane/__version__.py, openlane/scripts/openroad/common/set_global_connections.tcl, openlane/steps/openroad.py, openlane/steps/tclstep.py
* Reworked Tcl unsafe string escaping to use home-cooked functions instead of
"shlex"
---
Resolves #90
=> Fix Tcl String Escaping

Changelog.md, nix/magic.nix, openlane/__version__.py, openlane/scripts/magic/extract_spice.tcl, openlane/steps/magic.py
* Updated Magic to `952b20d`
* Added new variable, `MAGIC_EXT_SHORT_RESISTOR` to `Magic.SpiceExtraction`,
disabled by default
Originally reported by @urish, @tnt
=> Short Resistors in Magic Spice Extraction

Changelog.md, default.nix, requirements.txt
Better diagnostics on `enable` failures - turns out the transient failures were rate-limiting
=> Bump Volare to 0.11.2

.github/workflows/ci.yml
Volare PDKs are cached to help mitigate the transient but frequent rate-limiting issue encountered by the CI.
=> Cache PDKs in CI

requirements_docs.txt
Sphinx 7.2 has a number of breaking changes: https://github.com/sphinx-doc/sphinx/issues/11608
We've been running into one with furo specifically, where it thinks a `html_style` is set for some reason.
=> Pin Sphinx 7.1 (and other versions)

Changelog.md, openlane/__version__.py, openlane/scripts/openroad/sta/corner.tcl, openlane/scripts/openroad/sta/multi_corner.tcl.bk, openlane/steps/openroad.py
~ rename `clock__max_slew_violation__count` to `design__max_slew_violation__count`
~ fix clk skew metric aggregation to use `-inf` instead of `inf`
=> STA: rename max transition violations count metric 

openlane/flows/flow.py, openlane/logging/__init__.py, openlane/logging/logger.py, openlane/steps/openroad.py
* `Flow.start()` now registers two handlers, one for errors and one for warnings, and forwards them to `step_dir/{errors,warnings}.log` respectively
* Table no longer prints if log level is higher than `VERBOSE`
---
Resolves #140 
Resolves #147
=> Logging Adjustments

openlane/common/misc.py, openlane/common/toolbox.py, openlane/config/config.py, openlane/config/variable.py, openlane/scripts/klayout/open_design.py, openlane/scripts/klayout/render.py, openlane/scripts/klayout/stream_out.py, test/config/test_config.py
* Added a "dummy path" for macro translation purposes that always validates and is ignored by `self.toolbox.get_macro_views` 
* Made KLayout scripts more resilient to relative pathing
=> Macro Config Bugfixes

.github/workflows/ci.yml, Changelog.md, openlane/__main__.py, openlane/__version__.py, openlane/container.py
* Add new commandline options: `--docker-tty/--docker-no-tty`, controlling the `-t` flag of Docker and compatible container engines which allocates a virtual tty
* Convert CI to use `--dockerized` instead of a plain `docker run`
=> Add Docker TTY Commandline Flag + Have CI test `--dockerized` specifically

openlane/common/drc.py
Loading the drc.klayout.xml in recent KLayout results in an error: 
```
XML parser error: met4.2 is not a valid category path in line 1, column 251
```
Apparently, the category names needs to be surrounded by single quotes. After this fix, KLayout is able to load and show the DRC markers correctly. Verified with KLayout v0.28.10 on Windows 11.
=> Fix broken KLayout DRC Report

openlane/scripts/openroad/pdn.tcl
`PDN_CFG` was renamed to `FP_PDN_CFG` in 2.0.0b7. However, it was not renamed in pdn.tcl, so it is no longer possible to define a custom PDN configuration file.
I verified this fix with the Tiny Tapeout multiplexer: before this fix, hardening the mux controller failed with 2.0.0b7 (where as it worked on 2.0.0b6) since the custom PDN script is not loaded (causing the default PDN to be used, which in turn conflicts with some custom routing we have an causes DRC/LVS failures). 
After applying this fix on top of 2.0.0b7, I was able to harden the mux controller successfully and get similar results to the 2.0.0b6.
=> Fix broken FP_PDN_CFG

Changelog.md, openlane/__version__.py
* Added `PNR_SDC_FILE` to all OpenROAD steps
* Added `SIGNOFF_SDC_FILE` to `OpenROAD.STAPostPNR`
* Added `report_design_area_metrics` to OpenROAD scripts that potentially modify the layout
* Added comprehensive documentation on PDKs
* Added documentation for migrating the Macro object
* Added validation for unknown keys for the Macro object
* Added testing for `openlane.common.toolbox::Toolbox::create_blackbox_model`, `openlane.common.toolbox::Toolbox::get_lib_voltage`,  `openlane.flows.sequential::SequentialFlow::__init_subclass__`=
* Updated OpenROAD to `0a6d0fd`: **There is an API break in OpenDB APIs**:
* `odb.read_def` now takes a `dbTech` and a Path string instead of a
`dbDatabase` and a Path string.
* The `dbTech` object can be obtained via the `getTech` method on `dbDatabase` …
=> Release Beta 14

.github/test_sets/test_sets.yml, .gitignore, openlane/scripts/yosys/synthesize.tcl, openlane/steps/step.py, openlane/steps/verilator.py, openlane/steps/yosys.py
* Added latch design to fastest test set for both supported PDKs
* Latches are now reported as a lint error if the variable `LINTER_ERROR_ON_LATCH` is set to `True` (which it is by default)
* Fixed a race condition with `openlane/steps/step.py::Step::run_subprocess`
---
Resolves #194
=> Lint Error on Latch

openlane/common/toolbox.py
`output_log_path` in `toolbox.py` is formed from `self.tmp_dir` and `out_path` (line 419), but `out_path` already includes `self.tmp_dir` (line 379), causing flows to fail:
```
Traceback (most recent call last):
File "/home/nixos/designs/xspi_os/flow.py", line 33, in <module>
flow.start()
File "/nix/store/3ics23fpk3gzby2ys5cm648xgcwfpcch-python3.10-openlane/lib/python3.10/site-packages/openlane/flows/flow.py", line 553, in start
final_state, step_objects = self.run(
File "/nix/store/3ics23fpk3gzby2ys5cm648xgcwfpcch-python3.10-openlane/lib/python3.10/site-packages/openlane/flows/sequential.py", line 276, in run
current_state = step.start(
File "/nix/store/3ics23fpk3gzby2ys5cm648xgcwfpcch-python3.10-openlane/lib/python3.10/site-packages/openlane/steps/step.py", line 704, in start …
```
=> Fix log path in `create_blackbox_model`

openlane/steps/openroad.py
The hold and setup worst slacks values are better visualized in the summary table along with the violations count
=> + add Hold WS and Setup WS to the STAPostPNR summary table

openlane/steps/openroad.py, shell.nix
* Strips `_` alongside asterisks from corner names, which without that, files intended for corner patterns such as `max_*` would have the name `max_`
* Allows OpenLane plugins to be passed to `shell.nix` so plugins can reuse the `shell.nix` internally
=> Chomp underscores in corner patterns + Make shell.nix accept plugins

openlane/scripts/yosys/synthesize.tcl
It's actually useful to be able to run 'empty' designs through the flow and unfortunately 'show' command fails with "Nothing to show" ... So because the 'show' is just a "nice to have" make any failure non-fatal.
=> scripts/yosys: Tolerate 'show' failures as non-fatal

nix/yosys.nix
* Fixes a bug where the hash for Yosys 0.34 was replaced by its corresponding `yosys-abc` hash by accident
=> Fix Yosys Hash

openlane/steps/magic.py
Add `MAGIC_CAPTURE_ERRORS` to capture and throw errors generated by Magic.
---
Fixes https://github.com/efabless/openlane2/issues/239
Fixes https://github.com/efabless/openlane2/issues/238
Fixes https://github.com/efabless/openlane2/issues/237
=> Capture errors generated by Magic

docs/source/usage/migration/variables.md, openlane/config/flow.py, openlane/config/removals.py, openlane/scripts/openroad/floorplan.tcl, openlane/steps/openroad.py, shell.nix
* `OpenROAD.Floorplan`
* Added a new PDK variable, `EXTRA_SITES`, which specifies alternative sites to use for floorplanning (as overlapping rows) even when:
* Cells without double-heights are not used
* Double-height cells with missing or mislabeled LEF `SITE`s are used
* Removed `PLACE_SITE_HEIGHT` and `PLACE_SITE_WIDTH`: can be extracted via OpenROAD
---
Resolves #243 
Depends on https://github.com/efabless/openlane2-ci-designs/pull/6
Depends on https://github.com/efabless/openlane2-step-unit-tests/pull/10
=> Allow explicit declaration of double-height rows during floorplanning

openlane/scripts/yosys/synthesize.tcl
=> Fix `SYNTH_NO_FLAT` using an OpenLane 1-only environment variable

.github/test_sets/test_sets.yml
* Re-adds manual macro placement test to CI now that the DRC issues have been addressed
---
Depends on https://github.com/efabless/openlane2-ci-designs/pull/7
=> Re-add manual macro placement test to CI

openlane/scripts/magic/common/read.tcl, openlane/scripts/magic/get_bbox.tcl, openlane/steps/magic.py, openlane/steps/tclstep.py
* `Magic.StreamOut`:
* Fixed issue where black-boxed macros with non-north orientations are rotated around the incorrect point
* Updated to throw errors when `MAGIC_MACRO_STD_CELL_SOURCE` is set to `macro` and:
* Multiple GDS files are defined per macro
* A macro's GDS file does not have a PR boundary 
* `MagicStep` no longer overrides `run`, but does override `run_subprocess`
* Changed `manual_macro_placement_test` design to have a macro with orientation `FN` as a test for this functionality
---
Resolves https://github.com/efabless/openlane2/issues/256
Depends on https://github.com/efabless/openlane2-ci-designs/pull/8
=> `Magic.StreamOut`: Fix Black-Boxed Macros with non-`N` orientations

openlane/scripts/openroad/common/io.tcl
=> Allow gzipped spef files

default.nix
* Added a new argument to `default.nix`, `system`, as `builtins.currentSystem` is not available when using nix flakes (where in documentation it is described as "non-hermetic and impure": see https://nixos.wiki/wiki/Flakes). This change allows passing the system as argument and thus restores compatibility with nix flakes.
=> Nix: add system as input argument

openlane/scripts/openroad/rsz_timing_postcts.tcl, openlane/scripts/openroad/rsz_timing_postgrt.tcl, openlane/steps/openroad.py
* `OpenROAD.ResizerTimingPostCTS`, `OpenROAD.ResizerTimingPostGRT`:
* Added `PL_RESIZER_GATE_CLONING` and `GRT_RESIZER_GATE_CLONING` rspectively, which control `OpenROAD`'s ability when calling `repair_timing` (default: `true`)
=> `OpenROAD.ResizerTiming*`: Config Variable to Enable/Disable Cloning

openlane/flows/flow.py, openlane/steps/cvc_rv.py, openlane/steps/openroad.py
* `OpenROAD.CTS`, `CVCRV.ERC` (unused): Replaced legacy calls to `Fix legacy calls to `Step.run(self, …)`  causing crashes in some situations
=> Fix legacy calls to `Step.run(self, …)`

.github/workflows/ci.yml
* Fixed the CI failing to push the final Docker manifest properly because of an omission.
=> Hotfix: `push` -> `manifest push`

.github/workflows/ci.yml, default.nix, docker.nix, openlane/steps/odb.py, shell.nix
* Fixed an issue where Docker images did not properly have dependencies of dependencies set in `PYTHONPATH`.
* Fixed Docker images not having `TMPDIR` set by default.
* Removed `PYTHONPATH` from `default.nix` - OpenLane now passes its `site-packages` to subprocesses (less jank but still jank)
* Fixed IPM install command being rate-limited
* Fixed IPM caching order (the cache action should come first)
---
Resolves #307 
Depends on https://github.com/efabless/openlane2-step-unit-tests/pull/17
=> Fix Docker image `PATH` issues

.gitignore, openlane/flows/classic.py, openlane/steps/checker.py
* Added `Checker.SetupViolations `, `Checker.HoldViolations` to check setup/hold timing violations
* Add config variable `TIMING_VIOLATIONS_CORNERS`, which is a list of wildcards to match corners those steps will flag an error on.
* `Classic`:
* Added `Checker.SetupViolations`, `Checker.HoldViolations` to the end of the flow
* Both gated by `QUIT_ON_TIMING_VIOLATIONS`
* Each gated by `QUIT_ON_SETUP_VIOLATIONS`, `QUIT_ON_HOLD_VIOLATIONS` respectively
* Added `/designs` to `.gitignore`
* Added units test for `Checker.StepViolations` and `Checker.HoldViolations`
---
depends on: https://github.com/efabless/openlane2-step-unit-tests/pull/19
Fixes https://github.com/efabless/openlane2/issues/286
=> Timing Violation Checkers

flake.lock
This is the only thing gating Flake compatibility with some older versions of Nix.
=> Remove last modified attribute from `flake.lock`

openlane/config/flow.py, openlane/steps/yosys.py
* Renamed GPIO_PADS_PREFIX to GPIO_PAD_CELLS, accepting with translation behavior
* Created `TRISTATE_CELLS` for parity with OpenLane, accepting (multiple) wildcards and `TRISTATE_CELL_PREFIX` with translation behavior
* Added test for both hand-instantiating tri-state buffers AND high-impedance derived tri-state buffers
---
Fixes #285 
Depends on https://github.com/efabless/openlane2-step-unit-tests/pull/20
=> Allow cells matching `TRISTATE_CELLS` in `SYNTH_CHECKS_ALLOW_TRISTATE`

openlane/scripts/openroad/common/set_global_connections.tcl, openlane/scripts/openroad/gpl.tcl, openlane/steps/openroad.py
* `OpenROAD.*`
* Added regex matching check for patterns inside `PDN_MACRO_CONNECTIONS`
* Updated `PDN_MACRO_CONNECTIONS` documentation to highlight the fact the instance name is actually a regex
* Fix a bug in `PDN_MACRO_CONNECTION` related to double escaping of special characters. 
* `OpenROAD.GlobalPlacement`
* Added new variable `PL_WIRE_LENGTH_COEF` passed as `-init_wirelength_coef` to OpenROAD
=> Port features from OL1

openlane/config/flow.py, openlane/config/removals.py, openlane/scripts/openroad/common/io.tcl, openlane/scripts/openroad/cut_rows.tcl, openlane/scripts/openroad/tapcell.tcl, openlane/steps/common_variables.py, openlane/steps/odb.py, openlane/steps/openroad.py
* Universal Flow Variables
* Renamed `FP_WELLTAP_CELL` to `WELLTAP_CELL` with translation behavior
* Renamed `FP_ENDCAP_CELL` to `ENDCAP_CELL` with translation behavior
* **API Breaks**
* `CTS_ROOT_BUFFER`, `CTS_CLK_BUFFERS` and `CTS_MAX_CAP` all moved to `OpenROAD.CTS`
* `IGNORE_DISCONNECTED_MODULES` moved to `Odb.ReportDisconnectedPins`
* `GPL_CELL_PADDING` moved to `OpenROAD.GlobalPlacement`
* `DPL_CELL_PADDING` moved to steps that have the rest of the `dpl` variables
* `GRT_LAYER_ADJUSTMENTS` moved to steps that have the rest of the routing layer variables
* Moved `GRT_OBS` to `Odb.AddRoutingObstructions` as a deprecated name for `ROUTING_OBSTRUCTIONS`
* Removed `FP_CONTEXT_DEF`, `FP_CONTEXT_LEF`, and `FP_PADFRAME_CFG`: To be implemented
* Removed `LVS_INSERT_POWER_PINS`, `RUN_CVC`, …
=> Clean up universal flow variables

openlane/steps/step.py, test/steps/test_step.py
* `openlane.steps.Step`
* Fixed `run_subprocess` crashing upon a tool outputting gibberish - a `StepException` is raised now
---
Fixes #226
=> Handle non-UTF-8 outputs by subprocesses

docs/source/getting_started/migrants/index.md, docs/source/getting_started/newcomers/index.md
* Replaced Cachix's Nix installation guide with our Nix-based Installation guide in the Newcomers' Guide
=> Update Nix Installation instruction link in the Newcomers' guide

.github/workflows/ci.yml, openlane/steps/openroad.py
* `OpenROAD.GlobalPlacementSkipIO`:
* Fixed a bug where `PL_TARGET_DENSITY_PCT` is calculated base on `FP_CORE_UTIL`
in designs with `FP_SIZING` set to `absolute`. The behavior now matches
`OpenROAD.GlobalPlacement`.
=> Fix OpenROAD.GlobalPlacementSkipIO sometimes not using correct util

openlane/scripts/openroad/cts.tcl
* `OpenROAD.CTS`
* Fixed bug where an incorrect value was passed to the `-max_slew` option
=> Fix wrong value passed to CTS -max_slew

openlane/scripts/openroad/cts.tcl
* `OpenROAD.CTS`
* Fixed issue where no arguments were passed to `configure_cts_characterization`
=> Fix args not propagated to configure_cts_characterization

openlane/scripts/magic/lef.tcl
* `Magic.WriteLEF`
* Fixed bug where `MAGIC_WRITE_FULL_LEF` had its logic inverted
---
Resolves #428 
---
Just to be clear, this is my fault; despite the blame showing Sylvain.
=> Fix Logic Mixup

openlane/config/pdk_compat.py
* PDK backwards-compatibility script now skips migrating `LIB_*` if `LIB` already exists
* "Default" constraints made exclusive to `sky130` and `gf180mcu`
=> PDK Migration Adjustments

docs/source/usage/using_macros.md, openlane/flows/flow.py, openlane/scripts/odbpy/manual_macro_place.py, openlane/scripts/odbpy/reader.py, openlane/steps/openroad.py
* `OpenROAD.ManualMacroPlacement`
* **API Break**: Verilog names of macros are now considered instead of DEF names in the event of a mismatch (e.g. for instances with `[]` or `/` in the name.)
* `openlane.flows`
* `Flow` 
* `.start()` now supports new keyword argument `overwrite` that deletes run directories if they are non-empty
---
Depends on https://github.com/efabless/openlane2-ci-designs/pull/24
Resolves #409
=> Macro Verilog Name Consistency

openlane/common/toolbox.py, openlane/scripts/openroad/cts.tcl, openlane/steps/openroad.py, openlane/steps/verilator.py
* `OpenROAD.CTS`
* Made `CTS_MAX_CAP` a non-PDK value, and also optional as the values in the PDKs are bad and OpenROAD does a better job without it
* CTS no longer passes `MAX_TRANSITION_CONSTRAINT`, instead using a new variable `CTS_MAX_SLEW` if it exists
* `Verilator.Lint`
* Fixed issue where the order of files may not be preserved for macros
---
Issues reported by @mo-hosni
=> Fix Caravel Issues

openlane/config/pdk_compat.py, openlane/scripts/odbpy/io_place.py, openlane/scripts/openroad/ioplacer.tcl, openlane/steps/common_variables.py, openlane/steps/odb.py, openlane/steps/openroad.py
* `OpenROAD.IOPlacement`
* `FP_IO_VLENGTH`, `FP_IO_HLENGTH`, `FP_IO_MIN_DISTANCE` are now all optional PDK variables
* For PDKs that do not specify them, OpenROAD calculates default values based on the layers' rules
* `OpenROAD.CustomIOPlacement`
* `FP_IO_VLENGTH`, `FP_IO_HLENGTH` are now both optional PDK variables
* The values are now used properly instead of a taking the maximum of both for both kinds of pins
* For PDKs that do not specify them, the script calculates default values based on the layers' rules
=> Move some Pin-Placament Variables to PDK

Changelog.md, openlane/__version__.py, openlane/scripts/openroad/common/set_global_connections.tcl, openlane/steps/openroad.py
* `OpenROAD.*`
* Fixed alert about unmatched regexes in `PDN_MACRO_CONNECTIONS` not being
properly marked as an `[ERROR]`.
* Fixed crash when steps that generate OpenROAD alerts that are suppressed by
the flow experience a non-zero exit.
=> hotfix: OpenROAD alert crashes

Changelog.md, openlane/__version__.py, openlane/scripts/odbpy/disconnected_pins.py, openlane/steps/odb.py
* `Odb.ReportDisconnectedPins`
* Fixed table not being written to step directory 
* Fixed bug where table widths were not being set properly
* Fixed bug where pins with `USE SIGNAL` would be considered power pins
=> hotfix: logical errors in `Odb.ReportDisconnectedPins`

openlane/steps/yosys.py
* `Yosys.*Synthesis`
* Syntheses with `SYNTH_ELABORATE_ONLY` no longer report undriven nets as a check error (frequently for some top-level integrations, output pins are left undriven entirely to save space.) 
---
Resolves #387 
Depends on https://github.com/efabless/openlane2-ci-designs/pull/28
=> Ignore undriven checks when running `SYNTH_ELABORATE_ONLY`

.github/workflows/ci.yml, Makefile, default.nix, flake.nix, nix/create-docker.nix, nix/docker.nix, openlane/__main__.py, openlane/container.py
* Docker subprocess is now always run interactively and can be interrupted.
* Docker subprocess now run using `execlp`, replacing the Python interpreter.
* Docker image creation now uses a Nix derivation based on that of the official Nix Docker image, which includes a full Nix installation in the image (so users may add tools and apps in the container at their leisure.)
=> Include Nix in the OpenLane 2 Docker Image

Changelog.md, openlane/__version__.py, openlane/scripts/odbpy/power_utils.py, openlane/scripts/yosys/json_header.tcl
* `Odb.SetPowerConnections`
* Fixed bug where instances with special characters in their name and power
pins are not equal to those of the SCL would not get connected.
* Added assertion that exactly one pin is connected for every operation.
* `Yosys.GenerateJSONHeader`
* Netlist is now flattened so `Odb.SetPowerConnections` can properly set pins
for nested macros with power pin names not equal to those of the SCL.
* `test/designs/dual_spm`
* SPM macro now hardened with pin names `power`, `ground` (as to not match the standard cell pin names)
* Dual SPM now nests the macros in a thin wrapper to test that the SPM macro will get its power pins connected properly.
---
Depends on https://github.com/efabless/openlane2-ci-designs/pull/27
=> hotfix: flatten while generating JSON headers

openlane/env_info.py
Running `python -m openlane --dockerized` will crash if /etc/os-release or /etc/lsb-release has a non-empty line without `=`. These files can have comment lines (without `=`), and in some Linux distributions they indeed do.
=> Fix crash if /etc/os-release has comment lines

openlane/scripts/odbpy/defutil.py
A couple of changes in the way DEF template are used.
The first one is actually a fix needed for newer OpenROAD (and hence why I submitted it against this `update-openroad`branch).
They shouldn't break anything with older ones though. Anything that worked before should still work fine after those changes.
=> DEF template enhancement

Changelog.md, openlane/__version__.py, openlane/scripts/odbpy/diodes.py
* `Odb.DiodePortInsertion`, `Odb.DiodesOnPorts`
* Fixed bug where diodes were never inserted on outputs, and added unit tests to that effect.
---
Depends on https://github.com/efabless/openlane2-step-unit-tests/pull/33
=> hotfix: fix diodes on output ports not working

Changelog.md, flake.lock, openlane/__version__.py, openlane/flows/flow.py, openlane/scripts/openroad/common/io.tcl, openlane/scripts/openroad/pdn.tcl, openlane/steps/openroad.py, requirements.txt
* Fixed `--ef-save-views-to` saving to `signoff/<design>/openlane` instead of
`signoff/<design>/openlane-signoff` (which makes less sense but is the
established convention at Efabless.)
* `OpenROAD.*`
* Fixed environment contamination with deprecated variables that may be used
by user-supplied PDN or SDC files.
* `OpenROAD.GeneratePDN`
* Restored compatibility with some ancient OpenLane PDN config files.
* Updated `ioplace_parser` to `0.2.0`
* Fixes regressions in pin regular expression parsing.
=> Update `ioplace_parser` to fix regression

Changelog.md, openlane/__version__.py, requirements.txt
* Relaxed `rich` version range to allow Rich 13.
* Matches Volare's version range and allows CACE and OpenLane 2 to be installed in the same Python environment.
=> Relax Rich Range

Changelog.md, openlane/__version__.py, openlane/common/tpe.py, openlane/steps/openroad.py
* Fixed a deadlock in some situations because of `OpenROAD.STAPrePNR` using the
global thread-pool for OpenLane, which may be used to run the step itself.
---
Resolves #501
=> Fix Deadlock

openlane/config/variable.py, openlane/scripts/openroad/floorplan.tcl, openlane/steps/openroad.py
* `OpenROAD.Floorplan`
* Added soft placement obstructions via new variable `PL_SOFT_OBSTRUCTIONS`.
* `openlane.common.config`
* Trailing commas are now permitted when converting from a string format (which are necessary because of the ambiguity of lists of lists.)
=> Added soft placement obstructions to Floorplanning

.github/actions/build_nix/action.yml, .github/actions/setup_env/action.yml, .github/workflows/ci.yml, Changelog.md, openlane/common/__init__.py, openlane/common/misc.py, openlane/common/tpe.py, openlane/flows/cli.py, openlane/scripts/odbpy/power_utils.py, openlane/scripts/openroad/ioplacer.tcl, openlane/steps/klayout.py, openlane/steps/openroad.py, openlane/steps/yosys.py, pyproject.toml, test/steps/conftest.py, test/steps/excluded_step_tests
* `Odb.SetPowerConnections`
* Internally reworked pin detection behavior so power pins are found in the LEF first then matched in the Verilog, fixing a corner-cases where unconnected buses would be candidates for power pins, then promptly cause a crash as they only exist in the layout as separate pins.
* `OpenROAD.IOPlacement`, `OpenROAD.GlobalPlacementSkipIO`
* `FP_IO_MODE` renamed to `FP_PPL_MODE`: translation behavior for OpenLane 1-style `FP_IO_MODE` with integers added behind deprecated name `FP_IO_MODE`.
* `Yosys.*Synthesis`
* Restored filtering of `defparam` from output netlists to avoid surprisingly still extant OpenSTA limitation.
* Added file to exclude test purely to speed-up turnaround time for PRs (as sometimes a test would need to be deleted/temporarily disabled without …
=> Backwards Compatibility Fixes

.github/actions/build_nix/action.yml, .github/workflows/ci.yml, Readme.md, docs/source/getting_started/common/nix_installation/installation_linux.md, docs/source/getting_started/common/nix_installation/installation_macos.md, docs/source/getting_started/common/nix_installation/installation_win.md, flake.lock
* Installation documents now use the less-brittle Determinate Systems Nix installer, as well as adding warnings about the `apt` version of Nix.
* Added an OpenROAD Flow Scripts-inspired Diagram to the Readme.
* CI now uses Determinate Systems Nix Installer for all Nix installations as well as the Magic Nix Cache Action instead of the nonfunctional attempt at local file-based substituters
=> Add ORFS-inspired Diagram to Readme; use DetSys Nix Installer

Changelog.md, default.nix, flake.nix, nix/opensta.nix, pyproject.toml
* Bundled a downgraded OpenSTA bundled with OpenLane to work around critical bug for hierarchical static timing analysis: https://github.com/parallaxsw/OpenSTA/issues/82
* Version of OpenSTA linked against OpenROAD unchanged.
=> Bundle stable OpenSTA alongside OpenROAD's version

Changelog.md, docs/source/usage/using_macros.md, openlane/scripts/odbpy/power_utils.py, openlane/scripts/odbpy/reader.py, openlane/steps/odb.py, pyproject.toml, test/steps/excluded_step_tests
* `Odb.SetPowerConnections`
* Fixed an issue introduced in `2.1.1` where modules that are defined as part of hierarchical netlists would be considered macros and then cause a crash when they are inevitably not found in the design database. * Explicitly mention that macros that are not on the top level will not be connected, and emit warnings if a hierarchical netlist is detected.
* Updated macro documentation to further clarify how instances should be named and how names should be added to the configuration.
=> Fix regression in `2.1.1`

Changelog.md, openlane/scripts/yosys/synthesize.tcl, pyproject.toml
In the Yosys synthesis script the `hilomap` command used for techmapping constant drivers is called with the wrong arguments. For instance, for sky130 it runs
`hilomap -hicell sky130_fd_sc_hd__conb_1/HI -locell sky130_fd_sc_hd__conb_1/LO`
instead of
`hilomap -hicell sky130_fd_sc_hd__conb_1 HI -locell sky130_fd_sc_hd__conb_1 LO`
This results in the step being skipped and some warnings:
```
56. Executing HILOMAP pass (mapping to constant drivers).
Warning: Selection "sky130_fd_sc_hd__conb_1" did not match any module.
Warning: Selection "LO" did not match any object.
```
This is a regression from OpenLane 1.
=> Fix arguments passed to Yosys hilomap

Changelog.md, openlane/scripts/odbpy/defutil.py, pyproject.toml
When specifying non integer coordinates in `ROUTING_OBSTRUCTIONS`, the Odb.RemoveRoutingObstructions would fail as it would truncate the decimal part before trying to match the coordinate.
For example, the following config would fail on any project (due to 16.5 appearing in the coordinate list):
```json
"ROUTING_OBSTRUCTIONS": [
"met1 10 10 20 16.5"
],
```
=> Fix Odb.RemoveRoutingObstructions failing with non-integer coordinates

Changelog.md, openlane/scripts/openroad/sta/corner.tcl, pyproject.toml
* `OpenROAD.STA*PnR`:
* Fixed a bug in STA metrics where paths with exactly zero slack are counted as violations
* Added a test case for #505
---
Depends on https://github.com/efabless/openlane2-step-unit-tests/pull/37
Fixes #505
=> Fix Zero-Slack Paths Being Counted As Violations

Changelog.md, openlane/flows/synth_explore.py, openlane/steps/openroad.py, pyproject.toml
* `OpenROAD.CheckAntennas`
* Fixed table being printed to file with wrong width
* `OpenROAD.STA*PnR`
*  Fixed table being printed to file with wrong width
* `SynthesisExploration`
* Fixed table being printed to file with wrong width
=> Fix Table Being Printed to File With Wrong Width

Changelog.md, openlane/scripts/openroad/sta/corner.tcl, pyproject.toml
* `OpenROAD.STA*PnR`
* Fixed `timing__*_r2r__ws__corner` metrics reporting the wrong value
---
When getting ws (worst slack), the flow shouldn't skip positive slacks.
=> bugfix: fix wrong reported value for timing__*_r2r__ws__corner

Changelog.md, nix/create-shell.nix, nix/docker.nix, openlane/steps/odb.py, pyproject.toml
* `Odb.*`
* Fixed OpenROAD dropping user-set `PYTHONPATH` values.
* Use `NIX_PYTHONPATH` instead of `PYTHONPATH` in Docker and devshells
to avoid collisions with user-set `PYTHONPATH` variables.
=> bugfix: odb steps dropping PYTHONPATH

Changelog.md, openlane/steps/openroad.py, pyproject.toml
* `OpenROAD.WriteViews`
* Fixed step not being registered to factory object.
---
It was accidentally removed in https://github.com/efabless/openlane2/pull/280
=> bugfix: Register OpenROAD.WriteViews in step factory

Changelog.md, openlane/steps/pyosys.py, pyproject.toml
* `Yosys.JsonHeader`, `Yosys.Synthesis`
* Fixed `VERILOG_INCLUDE_DIRS` being a list of strings instead of a list of
`Path`s.
---
Resolves #615
=> bugfix: VERILOG_INCLUDE_DIRS not a list of Paths

openlane/scripts/pyosys/synthesize.py
* `Yosys.*Synthesis`
* Fixed crash when `SYNTH_NO_FLAT` is set to `true`.
---
Resolves #619
=> bugfix: crash when `SYNTH_NO_FLAT` is set to `true`

Changelog.md, docs/source/glossary.md, docs/source/usage/using_macros.md, openlane/common/misc.py, openlane/common/toolbox.py, openlane/scripts/pyosys/synthesize.py, openlane/scripts/pyosys/ys_common.py, openlane/steps/pyosys.py, pyproject.toml
* `Yosys.*`
* Fixed blackbox Verilog and lib models causing a crash if they are
gzipped and/or have the extension `.gz`.
* Relaxed requirement on `httpx` to include `0.28.X`, which has no removals
compared to `0.27.0`.
---
Resolves #622 
Resolves #627
=> hotfix: crash when macro lib files are gzipped

Changelog.md, openlane/scripts/openroad/floorplan.tcl, pyproject.toml
* `OpenROAD.Floorplan`
* Fixed an issue in `FP_SIZING`: `absolute` mode where if the die area's x0 > x1 or y0 > y1, the computed core area would no longer fit in the die area. Not that we recommend you ever do that, but technically OpenROAD allows it.
=> bugfix: `OpenROAD.Floorplan` core area calculation

Changelog.md, flake.lock, flake.nix, pyproject.toml
nix-eda 2.1.1 has an issue where Python overlays don't work properly AND gds-tk does not build successfully on Linux.
=> fix: update nix-eda for python overlays

openlane/steps/verilator.py
Similar to https://github.com/The-OpenROAD-Project/OpenLane/pull/2046
=> Use VERILOG_INCLUDE_DIRS in Verilator

Changelog.md, openlane/scripts/odbpy/diodes.py, openlane/scripts/openroad/floorplan.tcl, openlane/steps/odb.py, openlane/steps/openroad.py, pyproject.toml
This helps with a proprietary PDK.
Also make HEURISTIC_ANTENNA_THRESHOLD optional, missed in #662. Also helps with a proprietary PDK.
=> feat: add optional PDK variable to flip placement sites

Changelog.md, nix/openroad.nix, nix/patches/openroad/6743.patch, pyproject.toml
This fixes a crash when using the OpenROAD GUI on macOS.
=> fix: backport The-OpenROAD-Project/OpenROAD#6743

Changelog.md, openlane/scripts/pyosys/synthesize.py, pyproject.toml
=> bugfix: No $scopeinfo cell when flattening in ELABORATE_ONLY mode
