Changelog.md
openlane/__version__.py
openlane/config/builder.py

What is says on the tin. :slightly_smiling_face: Resolves #36.

Fix crash when SCL is specified via command-line

---

Changelog.md
Readme.md
docs/source/getting_started/nix_installation/index.md
openlane/__init__.py
openlane/__main__.py
openlane/plugins.py
openlane/scripts/openroad/common/io.tcl
setup.py

* Created a (very) rudimentary plugin system
* Added the ability to list detected plugins with flag `--list-plugins`
* Fixed a problem with reading SPEF files for macros
* Various documentation updates

Rudimentary Plugin System

---

Changelog.md
openlane/__version__.py
openlane/config/flow.py
openlane/config/variable.py
openlane/scripts/openroad/cts.tcl
openlane/steps/klayout.py
openlane/steps/openroad.py

* Made optional/default handling more straightforward to fix issue where
the default value of an Optional is not None.
* Fixed config var inheritance issue for `OpenROAD.ParasiticsSTA`

Various Variable Vexes

---

Changelog.md
openlane/__version__.py
openlane/config/macro.py
openlane/scripts/openroad/common/io.tcl
openlane/scripts/yosys/common.tcl
openlane/scripts/yosys/synthesize.tcl
openlane/steps/openroad.py
openlane/steps/yosys.py

* Added missing macro orientations
* Added missing `PDN_CFG` configuration variable
* Fixed crash when defining `SYNTH_READ_BLACKBOX_LIB`
* Streamlined all `read` messages in OpenROAD scripts and macro-related `read`
messages in Yosys scripts.
* Cleaned up `YosysStep` hierarchy
* Cleaned up `synthesize.tcl`
> Thanks @smunaut for the bug reports!
---
Resolves #58
Resolves #60 
Resolves #62 
Resolves #63

Various Bugfixes

---

Changelog.md
Readme.md
openlane/__version__.py
openlane/scripts/openroad/common/io.tcl
openlane/scripts/openroad/irdrop.tcl
openlane/scripts/openroad/sta/multi_corner.tcl
openlane/state/design_format.py
openlane/steps/openroad.py
openlane/steps/tclstep.py

Fix LIB/SDF Writing

---

Changelog.md
nix/magic.nix
openlane/__version__.py

Revert Magic to a33d7b7

---

.github/test_sets/test_sets.yml
Changelog.md
designs/io_placer/config.json
designs/manual_macro_placement_test/config.json
openlane/__version__.py
openlane/scripts/magic/def/read.tcl
openlane/scripts/magic/lef.tcl
openlane/steps/magic.py

* Added `io_placer` and `manual_macro_placemnt_test` to CI
* Fixed `MAGTYPE` for `Magic.WriteLEF`
* Fixed bug with reading `EXTRA_LEFS` in Magic steps

Magic Fixes

---

Changelog.md
openlane/__version__.py
openlane/scripts/openroad/common/resizer.tcl
openlane/scripts/openroad/cts.tcl
openlane/scripts/openroad/repair_design.tcl
openlane/scripts/openroad/rsz_timing_postcts.tcl
openlane/scripts/openroad/rsz_timing_postgrt.tcl
openlane/steps/common_variables.py
openlane/steps/openroad.py
openlane/utils/toolbox.py

* Added support for multiple corners during CTS using the `CTS_CORNERS` variable
* Added support for multiple corners during resizer steps using the `RSZ_CORNERS` variable
* Internally reworked OpenROAD resizer and CTS steps to share a common base class
---
Resolves #49

Multi-corner CTS & Resizing

---

Changelog.md
nix/magic.nix
nix/netgen.nix
nix/patches/yosys/fix-clang-build.patch
nix/yosys-abc.nix
nix/yosys.nix
openlane/__main__.py
openlane/__version__.py
openlane/common/__init__.py
openlane/common/generic_dict.py
openlane/scripts/yosys/common.tcl
openlane/scripts/yosys/json_header.tcl
openlane/scripts/yosys/synthesize.tcl
openlane/steps/yosys.py

* Update Magic, Netgen, and Yosys
* Made `SYNTH_ELABORATE_ONLY` functional
* Minor internal rearchitecture of `common` and commandline options

Update Tools + Synth Elaborate Only

---

Changelog.md
openlane/__version__.py
openlane/scripts/yosys/json_header.tcl
openlane/scripts/yosys/synthesize.tcl

* Made designs synthesized by Yosys keep their name after `chparam`

Fix `chparam` synthesis issue

---

requirements_docs.txt

Sphinx 7.2.2 released with a fix for the Furo bug: https://github.com/sphinx-doc/sphinx/issues/11608#issuecomment-1682666493

Bump Sphinx to 7.2.2

---

docs/source/usage/chip_integration.md

docs: fix value for `lib` in Macro object

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
docs/_templates/generate_configvar_docs/common_pdk_vars.md
docs/_templates/generate_configvar_docs/common_vars.md
docs/source/reference/pin_placement_cfg.md
docs/source/usage/chip_integration.md
openlane/__init__.py
openlane/config/variable.py
openlane/env_info.py
openlane/flows/flow.py
openlane/steps/step.py
setup.py

* Fixed a number of broken links
* Fixed a number of invalid docstrings
* Changed all auto-generated anchors to be exclusively in lowercase characters
* Added GitHub Issue Templates

Documentation Fixes + Issue Templates

---

Changelog.md
openlane/__version__.py
openlane/flows/classic.py
openlane/flows/flow.py
openlane/flows/sequential.py

Compiled changelog for beta 13
[ci ets]

Release Beta 13

---

openlane/config/config.py
openlane/config/pdk_compat.py
openlane/config/preprocessor.py
openlane/flows/flow.py
openlane/steps/openroad.py

* Sort `glob` results, as glob returns files in an arbitrary order on some filesystems: https://docs.python.org/3.8/library/glob.html?highlight=sorted

Fix `glob` nondeterminism

---

openlane/config/variable.py

Fixes https://github.com/efabless/openlane2/issues/251

Expose all available orientations for MACRO variables

---

openlane/steps/common_variables.py

This matches OpenLane. It is also the default for OpenROAD.

Set default value FP_PDN_SKIPTRIM to false

---

openlane/scripts/odbpy/defutil.py

https://github.com/efabless/openlane2-step-unit-tests/pull/12

Fix a bug where routing obstructions may not all be applied

---

.github/test_sets/test_sets.yml

+ Port aes_user_project_wrapper from OpenLane 1
+ Add user_proj_timer from https://github.com/efabless/openframe_timer_example/tree/main/openlane/user_proj_timer
---
Depends on https://github.com/efabless/openlane2-ci-designs/pull/10

Add new designs 

---

openlane/scripts/yosys/synthesize.tcl

* `Yosys.Synthesis`
* Fixed bug where custom technology maps were not properly applied

Replace deprecated variables in `synthesize.tcl`

---

openlane/steps/openroad.py

* `OpenROAD.CheckAntennas`:
* Added new `antenna_summary.rpt` file with a summary table for antennas matching that of OpenLane 1
e.g.
```
┏━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━┓
┃ Partial/Required ┃ Required ┃ Partial ┃ Net                         ┃ Pin          ┃ Layer ┃
┡━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━┩
│ 2.98             │ 400.00   │ 1191.22 │ net389                      │ fanout1409/A │ met1  │
│ 2.14             │ 400.00   │ 855.22  │ _12240_                     │ _16625_/A    │ met1  │
│ 2.07             │ 400.00   │ 828.39  │ _11346_                     │ _31660_/S    │ met1  │
│ 2.02             │ 400.00   │ 807.56  │ net817                      │ _19003_/A    │ met1 …
```

Add antenna report summary table

---

openlane/steps/misc.py

* `Misc.ManufacturabilityReport`
* Fixed LVS metric names not being updated
* Wording tweak

Fix manufacturability report

---

openlane/flows/flow.py

* `__main__`
* Fixed `--ef-save-views-to` not saving `.mag`, `.gds` views
---
Resolves #406

Add missing views in `--ef-save-views-to`

---

openlane/common/tcl.py

The current implementation for parsing Tcl config files fails to catch environment variables defined in subordinate `.tcl` files included from the main `.tcl` with the `source` command. This breaks openlane1 compatibility for almost every user design submitted to Tiny Tapeout.
Tcl config files are parsed using `TclUtils._eval_env()`. The current version
- modifies `os.environ` to provide inputs to the script
- runs the script
- converts `::env` to numbered variables on the tcl side
- rolls back the changes to `os.environ`
- reads the numbered variables from tcl back into python
- filters the results to entries appearing in `set ::env(...)` constructs in the script
The last step is there to filter out entries inherited from the environment, but it also filters out entries defined in …

Rewrite code for parsing Tcl config files

---

openlane/__main__.py
openlane/flows/cli.py
openlane/flows/flow.py

* Exposed Flow.start(overwrite=) as `--overwrite`, which removes a run directory before running the flow (if it exists)
---
resolves #499

cli: add `--overwrite`

---

.github/test_sets/test_sets.yml
Changelog.md
flake.nix
nix/patches/yosys/async_rules.patch
pyproject.toml

Depends on https://github.com/efabless/openlane2-ci-designs/pull/38

misc: patch yosys to fix bug

---

Changelog.md
openlane/scripts/openroad/cts.tcl
openlane/steps/openroad.py
pyproject.toml

Pretty self-explanatory.
---
Resolves #644

feat: wildcards in cts_clk_buffers
